import streamlit as st
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from pathlib import Path
import time

# --- 1. PAGE CONFIG ---
st.set_page_config(
    page_title="VIX Spread Terminal",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- 2. CONFIGURATION ---
CSV_PATH = Path("vix_spread_data.csv")
SPREADS_CONFIG_NAMES = {
    "en": {"Feb 2026": "Feb 2026", "Mar 2026": "Mar 2026"},
    "zh": {"Feb 2026": "2026年2月", "Mar 2026": "2026年3月"}
}
# Internal keys must match the prefixes generated by the fetcher script
SPREAD_KEYS = ["Feb 2026", "Mar 2026"]

# --- 3. TRANSLATIONS (Identical to original) ---
TRANSLATIONS = {
    "en": {
        "page_title": "VIX Spread Terminal",
        "header_subtitle": "VIX Bullish Call Spread Monitor",
        "header_title": "Multi-Expiry Terminal",
        "live_data": "STATIC DATA",  # Changed badge text
        "configuration": "Configuration",
        "language": "Language",
        "active_spreads": "Active Spreads",
        "select_expiries": "Select expiries to monitor",
        "data_settings": "Data Settings",
        "historical_lookback": "Historical Lookback",
        "days": "days",
        "refresh_interval": "Refresh Interval",
        "auto_refresh": "Auto Refresh",
        "refresh": "🔄 Reload CSV",
        "last_updated": "Last Data Point",
        "long_leg": "Long Leg (C20)",
        "short_leg": "Short Leg (C30)",
        "net_spread": "Net Spread",
        "volume": "Vol",
        "spread_title": "Spread",
        "individual_legs": "Individual Legs",
        "volume_title": "Volume",
        "mean": "Mean",
        "view_daily_log": "📁 View Data Source",
        "no_file": "❌ 'vix_spread_data.csv' not found. Run 'vix_data_fetcher.py' first.",
        "select_spread_warning": "Please select at least one spread expiry in the sidebar.",
    },
    "zh": {
        "page_title": "VIX价差终端",
        "header_subtitle": "VIX看涨期权价差监控",
        "header_title": "多到期日终端",
        "live_data": "静态数据",
        "configuration": "配置",
        "language": "语言",
        "active_spreads": "活跃价差",
        "select_expiries": "选择要监控的到期日",
        "data_settings": "数据设置",
        "historical_lookback": "历史回溯",
        "days": "天",
        "refresh_interval": "刷新间隔",
        "auto_refresh": "自动刷新",
        "refresh": "🔄 重新加载CSV",
        "last_updated": "最新数据",
        "long_leg": "多头 (C20)",
        "short_leg": "空头 (C30)",
        "net_spread": "净价差",
        "volume": "成交量",
        "spread_title": "价差",
        "individual_legs": "单腿价格",
        "volume_title": "成交量",
        "mean": "均值",
        "view_daily_log": "📁 查看源数据",
        "no_file": "❌ 未找到 'vix_spread_data.csv'。请先运行 'vix_data_fetcher.py'。",
        "select_spread_warning": "请在侧边栏中选择至少一个价差到期日。",
    }
}

# --- 4. SESSION STATE ---
if 'language' not in st.session_state:
    st.session_state.language = 'zh'

def t(key):
    return TRANSLATIONS[st.session_state.language].get(key, key)

# --- 5. ADAPTIVE CSS (Identical to original) ---
st.markdown("""
<style>
    @import url('https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;600;700&family=Plus+Jakarta+Sans:wght@400;500;600;700&family=Noto+Sans+SC:wght@400;500;600;700&display=swap');
    
    .dashboard-header {
        background: linear-gradient(90deg, rgba(38,166,154,0.12) 0%, transparent 50%);
        border-bottom: 1px solid rgba(38,166,154,0.25);
        padding: 20px 30px;
        margin: -1rem -1rem 2rem -1rem;
        display: flex;
        justify-content: space-between;
        align-items: center;
    }
    .header-title {
        font-family: 'Plus Jakarta Sans', 'Noto Sans SC', sans-serif;
        font-size: 28px;
        font-weight: 700;
        letter-spacing: -0.5px;
    }
    .header-subtitle {
        font-family: 'JetBrains Mono', 'Noto Sans SC', monospace;
        font-size: 12px;
        color: #26a69a;
        letter-spacing: 2px;
        text-transform: uppercase;
    }
    .live-badge {
        display: inline-flex;
        align-items: center;
        gap: 8px;
        background: rgba(38,166,154,0.12);
        border: 1px solid rgba(38,166,154,0.35);
        padding: 8px 16px;
        border-radius: 20px;
        font-family: 'JetBrains Mono', 'Noto Sans SC', monospace;
        font-size: 11px;
        color: #26a69a;
    }
    .live-dot {
        width: 8px;
        height: 8px;
        background: #26a69a;
        border-radius: 50%;
    }
    .metric-card {
        border-radius: 12px;
        padding: 24px;
        position: relative;
        overflow: hidden;
        transition: all 0.3s ease;
        border: 1px solid rgba(128, 128, 128, 0.25);
        background: rgba(128, 128, 128, 0.06);
        box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);
    }
    .metric-card:hover {
        transform: translateY(-2px);
        border-color: rgba(38, 166, 154, 0.4);
        box-shadow: 0 4px 16px rgba(0, 0, 0, 0.12);
    }
    .metric-label {
        font-family: 'Plus Jakarta Sans', 'Noto Sans SC', sans-serif;
        font-size: 11px;
        font-weight: 600;
        letter-spacing: 1.5px;
        text-transform: uppercase;
        margin-bottom: 8px;
        opacity: 0.7;
    }
    .metric-value {
        font-family: 'JetBrains Mono', monospace;
        font-size: 36px;
        font-weight: 700;
        line-height: 1;
    }
    .metric-delta {
        font-family: 'JetBrains Mono', monospace;
        font-size: 13px;
        font-weight: 600;
        margin-top: 8px;
        display: inline-flex;
        align-items: center;
        gap: 4px;
        padding: 4px 10px;
        border-radius: 6px;
    }
    .delta-positive { color: #26a69a; background: rgba(38,166,154,0.15); }
    .delta-negative { color: #ef5350; background: rgba(239,83,80,0.15); }
    .delta-neutral { color: #9e9e9e; background: rgba(158,158,158,0.15); }
    
    .volume-text {
        font-family: 'JetBrains Mono', 'Noto Sans SC', monospace;
        font-size: 12px;
        margin-top: 8px;
        opacity: 0.7;
    }
</style>
""", unsafe_allow_html=True)

# --- 6. DATA LOADER ---
@st.cache_data
def load_data(csv_path):
    if not csv_path.exists():
        return None
    try:
        df = pd.read_csv(csv_path)
        
        # 1. Ensure Date is datetime
        df["Date"] = pd.to_datetime(df["Date"])
        df = df.sort_values("Date")
        
        # 2. FORCE NUMERIC CONVERSION [CRITICAL FIX]
        # This converts any "text numbers" into real numbers for the chart
        cols_to_convert = [c for c in df.columns if c != "Date"]
        for col in cols_to_convert:
            df[col] = pd.to_numeric(df[col], errors='coerce')
            
        return df
    except Exception as e:
        st.error(f"Error loading data: {e}")
        return None

# --- 7. CHART FUNCTION ---
# [REPLACE THE create_spread_chart FUNCTION WITH THIS]
def create_spread_chart(df: pd.DataFrame, spread_name: str, lang: str):
    prefix = spread_name.replace(" ", "_")
    
    # Check if columns exist
    if f"{prefix}_Spread" not in df.columns:
        return go.Figure()

    # Prep Plot Data
    plot_df = pd.DataFrame(index=df["Date"])
    
    # --- FIX: ADD .values HERE ---
    # We use .values to ignore index alignment issues
    plot_df["Spread"] = df[f"{prefix}_Spread"].values
    plot_df["Long"] = df[f"{prefix}_Long_Price"].values
    plot_df["Short"] = df[f"{prefix}_Short_Price"].values
    plot_df["Volume"] = df[f"{prefix}_Total_Volume"].values
    
    # Force ensure numeric (just in case)
    plot_df = plot_df.apply(pd.to_numeric, errors='coerce')
    
    has_volume = plot_df["Volume"].sum() > 0

    spread_label = TRANSLATIONS[lang]["spread_title"]
    legs_label = TRANSLATIONS[lang]["individual_legs"]
    volume_label = TRANSLATIONS[lang]["volume_title"]
    mean_label = TRANSLATIONS[lang]["mean"]
    display_name = SPREADS_CONFIG_NAMES[lang].get(spread_name, spread_name)

    # Subplots
    if has_volume:
        fig = make_subplots(
            rows=3, cols=1,
            row_heights=[0.5, 0.25, 0.25],
            shared_xaxes=True,
            vertical_spacing=0.08,
            subplot_titles=(f"{display_name} {spread_label}", legs_label, volume_label)
        )
    else:
        fig = make_subplots(
            rows=2, cols=1,
            row_heights=[0.6, 0.4],
            shared_xaxes=True,
            vertical_spacing=0.1,
            subplot_titles=(f"{display_name} {spread_label}", legs_label)
        )

    # 1. Spread Trace
    fig.add_trace(go.Scatter(
        x=plot_df.index, y=plot_df["Spread"],
        mode='lines', name=spread_label,
        line=dict(color='#26a69a', width=2.5),
        fill='tozeroy', fillcolor='rgba(38,166,154,0.15)',
        hovertemplate=f'<b>{spread_label}</b>: %{{y:.2f}}<extra></extra>'
    ), row=1, col=1)

    # Mean Line
    mean_val = plot_df["Spread"].mean()
    fig.add_hline(y=mean_val, line_dash="dash", line_color="#9e9e9e",
                 annotation_text=f"{mean_label}: {mean_val:.2f}", row=1, col=1)

    # 2. Legs Traces
    fig.add_trace(go.Scatter(
        x=plot_df.index, y=plot_df["Long"], mode='lines', name='C20 (Long)',
        line=dict(color='#42a5f5', width=1.5)
    ), row=2, col=1)
    
    fig.add_trace(go.Scatter(
        x=plot_df.index, y=plot_df["Short"], mode='lines', name='C30 (Short)',
        line=dict(color='#ab47bc', width=1.5)
    ), row=2, col=1)

    # 3. Volume Trace
    if has_volume:
        fig.add_trace(go.Bar(
            x=plot_df.index, y=plot_df["Volume"], name=volume_label,
            marker_color='rgba(38,166,154,0.5)'
        ), row=3, col=1)

    # Layout
    fig.update_layout(
        height=550 if has_volume else 450,
        plot_bgcolor='rgba(0,0,0,0)',
        paper_bgcolor='rgba(0,0,0,0)',
        font=dict(family="JetBrains Mono, Noto Sans SC, monospace", size=11),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1, bgcolor='rgba(0,0,0,0)'),
        margin=dict(l=60, r=30, t=80, b=50),
        hovermode='x unified',
        showlegend=True
    )
    fig.update_xaxes(gridcolor='rgba(128,128,128,0.2)', showgrid=True, zeroline=False)
    fig.update_yaxes(gridcolor='rgba(128,128,128,0.2)', showgrid=True, zeroline=False)
    
    return fig

# --- 8. SIDEBAR ---
with st.sidebar:
    st.markdown(f"## ⚙️ {t('configuration')}")
    st.markdown("---")
    
    # Language
    st.markdown(f"**{t('language')}**")
    if st.session_state.language == 'en':
        if st.button("中文", key='lang_zh'):
            st.session_state.language = 'zh'
            st.rerun()
    else:
        if st.button("English", key='lang_en'):
            st.session_state.language = 'en'
            st.rerun()
    
    st.markdown("---")
    st.markdown(f"### {t('active_spreads')}")
    
    # Spread Selection
    spread_display_names = [SPREADS_CONFIG_NAMES[st.session_state.language][s] for s in SPREAD_KEYS]
    selected_display = st.multiselect(
        t('select_expiries'),
        options=spread_display_names,
        default=spread_display_names
    )
    # Map back to internal keys
    display_map = {v: k for k, v in SPREADS_CONFIG_NAMES[st.session_state.language].items()}
    active_spreads = [display_map[d] for d in selected_display]
    
    st.markdown("---")
    st.markdown(f"### {t('data_settings')}")
    
    lookback_days = st.selectbox(
        t('historical_lookback'),
        options=[30, 60, 90, 180, 365, 9999],
        index=2,
        format_func=lambda x: f"{x} {t('days')}" if x < 9999 else "All"
    )
    
    st.markdown("---")
    
    # Simple Manual Refresh Button
    if st.button(t('refresh'), width='stretch'):
        # Clear cache to force a re-read of the CSV file
        st.cache_data.clear()
        st.rerun()

# --- 9. MAIN DASHBOARD ---
st.markdown(f"""
<div class="dashboard-header">
    <div>
        <div class="header-subtitle">{t('header_subtitle')}</div>
        <div class="header-title">{t('header_title')}</div>
    </div>
    <div class="live-badge">
        <div class="live-dot"></div>
        {t('live_data')}
    </div>
</div>
""", unsafe_allow_html=True)

if not active_spreads:
    st.warning(t('select_spread_warning'))
    st.stop()

# --- LOAD DATA ---
full_df = load_data(CSV_PATH)

if full_df is None or full_df.empty:
    st.error(t('no_file'))
    st.stop()

# Filter by lookback
if lookback_days < 9999:
    cutoff = pd.Timestamp.now() - pd.Timedelta(days=lookback_days)
    df_chart = full_df[full_df["Date"] >= cutoff]
else:
    df_chart = full_df

# Get Last Row and Prev Row for Metrics
latest = full_df.iloc[-1]
prev = full_df.iloc[-2] if len(full_df) > 1 else latest

st.caption(f"{t('last_updated')}: {latest['Date'].strftime('%Y-%m-%d')}")

# --- TABS & METRICS ---
tab_names = [SPREADS_CONFIG_NAMES[st.session_state.language][s] for s in active_spreads]
tabs = st.tabs(tab_names)

for tab, spread_name in zip(tabs, active_spreads):
    with tab:
        prefix = spread_name.replace(" ", "_")
        
        # 1. METRICS
        # Fetch values safely
        def get_val(row, key, default=0.0):
            val = row.get(key, default)
            return 0.0 if pd.isna(val) else val
            
        cur_long = get_val(latest, f"{prefix}_Long_Price")
        cur_short = get_val(latest, f"{prefix}_Short_Price")
        cur_spread = get_val(latest, f"{prefix}_Spread")
        cur_l_vol = get_val(latest, f"{prefix}_Long_Volume")
        cur_s_vol = get_val(latest, f"{prefix}_Short_Volume")
        
        prev_long = get_val(prev, f"{prefix}_Long_Price")
        prev_short = get_val(prev, f"{prefix}_Short_Price")
        prev_spread = get_val(prev, f"{prefix}_Spread")
        
        # Deltas
        d_long = cur_long - prev_long
        d_short = cur_short - prev_short
        d_spread = cur_spread - prev_spread

        # Render Columns
        c1, c2, c3 = st.columns(3)
        
        def render_metric(col, label, val, delta, vol=None):
            delta_cls = "positive" if delta > 0 else "negative" if delta < 0 else "neutral"
            sign = "+" if delta > 0 else ""
            arrow = "▲" if delta > 0 else "▼" if delta < 0 else "−"
            
            html = [
                '<div class="metric-card">',
                f'<div class="metric-label">{label}</div>',
                f'<div class="metric-value">{val:.2f}</div>',
                f'<div class="metric-delta delta-{delta_cls}">{arrow} {sign}{delta:.2f}</div>'
            ]
            if vol is not None:
                html.append(f'<div class="volume-text">{t("volume")}: {int(vol):,}</div>')
            else:
                html.append('<div class="volume-text">&nbsp;</div>')
            html.append('</div>')
            
            col.markdown("".join(html), unsafe_allow_html=True)
            
        render_metric(c1, t('long_leg'), cur_long, d_long, cur_l_vol)
        render_metric(c2, t('short_leg'), cur_short, d_short, cur_s_vol)
        render_metric(c3, t('net_spread'), cur_spread, d_spread)
        
        st.markdown("---")
        
        # 2. CHART
        fig = create_spread_chart(df_chart, spread_name, st.session_state.language)
        st.plotly_chart(fig, width='stretch', theme="streamlit")

# --- DATA TABLE ---
st.markdown("---")
with st.expander(t('view_daily_log'), expanded=False):
    st.dataframe(full_df.sort_values("Date", ascending=False), width='stretch')

